/// Flutter icons Socicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Socicon
///      fonts:
///       - asset: fonts/Socicon.ttf
///
/// 
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class Socicon2 {
  Socicon2._();

  static const _kFontFam = 'Socicon2';
  static const _kFontPkg = null;

  static const IconData github = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_1 = IconData(0xf31a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
